/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\esotericsean\Projects\Game Boy Programming\25_SuzyMoveTest\GBTD\suzy_bg_test.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BGMapWidth 20
#define BGMapHeight 18
#define BGMapBank 0

#define BGMap BGMapPLN0
extern unsigned char BGMapPLN0[];
extern unsigned char BGMapPLN1[];

/* End of BGMAP.H */
