/*

 SuzySprites.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 36

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SuzySpritesSpritesBank 0

/* Gameboy Color palette 0 */
#define SuzySpritesCGBPal0c0 32767
#define SuzySpritesCGBPal0c1 20253
#define SuzySpritesCGBPal0c2 7505
#define SuzySpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SuzySpritesCGBPal1c0 32767
#define SuzySpritesCGBPal1c1 20253
#define SuzySpritesCGBPal1c2 12666
#define SuzySpritesCGBPal1c3 0

/* CGBpalette entries. */
extern unsigned char SuzySpritesCGB[];

/* Start of tile array. */
extern unsigned char SuzySprites[];

/* End of SuzySprites.H */
