/*

 SUZY2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 36

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Suzy2Bank 0

/* Super Gameboy palette 0 */
#define Suzy2SGBPal0c0 6076
#define Suzy2SGBPal0c1 8935
#define Suzy2SGBPal0c2 6596
#define Suzy2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Suzy2SGBPal1c0 6076
#define Suzy2SGBPal1c1 8935
#define Suzy2SGBPal1c2 6596
#define Suzy2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Suzy2SGBPal2c0 6076
#define Suzy2SGBPal2c1 8935
#define Suzy2SGBPal2c2 6596
#define Suzy2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Suzy2SGBPal3c0 6076
#define Suzy2SGBPal3c1 8935
#define Suzy2SGBPal3c2 6596
#define Suzy2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Suzy2CGBPal0c0 32767
#define Suzy2CGBPal0c1 20253
#define Suzy2CGBPal0c2 7505
#define Suzy2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define Suzy2CGBPal1c0 32767
#define Suzy2CGBPal1c1 20253
#define Suzy2CGBPal1c2 12666
#define Suzy2CGBPal1c3 0

/* Gameboy Color palette 2 */
#define Suzy2CGBPal2c0 6076
#define Suzy2CGBPal2c1 8935
#define Suzy2CGBPal2c2 6596
#define Suzy2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define Suzy2CGBPal3c0 6076
#define Suzy2CGBPal3c1 8935
#define Suzy2CGBPal3c2 6596
#define Suzy2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define Suzy2CGBPal4c0 6076
#define Suzy2CGBPal4c1 8935
#define Suzy2CGBPal4c2 6596
#define Suzy2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define Suzy2CGBPal5c0 6076
#define Suzy2CGBPal5c1 8935
#define Suzy2CGBPal5c2 6596
#define Suzy2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define Suzy2CGBPal6c0 6076
#define Suzy2CGBPal6c1 8935
#define Suzy2CGBPal6c2 6596
#define Suzy2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Suzy2CGBPal7c0 6076
#define Suzy2CGBPal7c1 8935
#define Suzy2CGBPal7c2 6596
#define Suzy2CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char Suzy2CGB[];
/* Start of tile array. */
extern unsigned char Suzy2[];

/* End of SUZY2.H */
