/*

 SUZY.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 36

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SuzyBank 0

/* Super Gameboy palette 0 */
#define SuzySGBPal0c0 6076
#define SuzySGBPal0c1 8935
#define SuzySGBPal0c2 6596
#define SuzySGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SuzySGBPal1c0 6076
#define SuzySGBPal1c1 8935
#define SuzySGBPal1c2 6596
#define SuzySGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SuzySGBPal2c0 6076
#define SuzySGBPal2c1 8935
#define SuzySGBPal2c2 6596
#define SuzySGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SuzySGBPal3c0 6076
#define SuzySGBPal3c1 8935
#define SuzySGBPal3c2 6596
#define SuzySGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SuzyCGBPal0c0 32767
#define SuzyCGBPal0c1 20253
#define SuzyCGBPal0c2 7505
#define SuzyCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SuzyCGBPal1c0 32767
#define SuzyCGBPal1c1 20253
#define SuzyCGBPal1c2 12666
#define SuzyCGBPal1c3 0

/* Gameboy Color palette 2 */
#define SuzyCGBPal2c0 6076
#define SuzyCGBPal2c1 8935
#define SuzyCGBPal2c2 6596
#define SuzyCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define SuzyCGBPal3c0 6076
#define SuzyCGBPal3c1 8935
#define SuzyCGBPal3c2 6596
#define SuzyCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SuzyCGBPal4c0 6076
#define SuzyCGBPal4c1 8935
#define SuzyCGBPal4c2 6596
#define SuzyCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SuzyCGBPal5c0 6076
#define SuzyCGBPal5c1 8935
#define SuzyCGBPal5c2 6596
#define SuzyCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SuzyCGBPal6c0 6076
#define SuzyCGBPal6c1 8935
#define SuzyCGBPal6c2 6596
#define SuzyCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SuzyCGBPal7c0 6076
#define SuzyCGBPal7c1 8935
#define SuzyCGBPal7c2 6596
#define SuzyCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char SuzyCGB[];
/* Start of tile array. */
extern unsigned char Suzy[];

/* End of SUZY.H */
